### ISSUE TITLE
Créer son CV quand on a pas encore de compte Zenika

### ISSUE THREAD

**Issue by ArnaudBuisine** [Zenika/Zenika-Resume#18]
Nous demandons systématiquement aux nouveaux arrivants Zenika de créer leur CV au format Zenika 1 voire 2 mois avant leur arrivée. Or à ce moment là ils n'ont pas de compte Zenika et donc pas d'accès à l'outil générateur de CV.
Il faudrait pouvoir leur créer un compte avec des droits spéciaux ne leur permettant que d'accéder et modifier leur CV sans accès à tout le reste (hors aide of course)

**Comment by hgwood** [comment]
Done.
