### ISSUE TITLE
Firefox, incapacité a voir la liste des resumés

### ISSUE THREAD

**Issue by LaurentTardif** [Zenika/Zenika-Resume#19]
En utilisant firefox, quand on clic sur "liste de tous les cv", cela redemande une authentification, et ca renvoie sur la page du cv par defaut ..... 

Le fixe n'est pas super urgent puisque je peux utiliser chrome ....

**Comment by hgwood** [comment]
Confirmer que ceci est toujours d'actualité après #33

**Comment by LaurentTardif** [comment]
a priori c'est tout bon, par contre dans "my resume" je n'ai rien ... par contre, je vois bien ceux que j'ai edité ... recherche : "tardif", ya une typo dans un de mes noms, mais je pense que le "my resume" se base sur l'ownership et pas le nom du fichier ?

**Comment by hgwood** [comment]
Tout à fait :) Merci de ton retour

@T3kstiil3 est-ce qu'on peut s'approprier un CV a posteriori ?

**Comment by T3kstiil3** [comment]
Hello, oui on peut.
Il faut juste renseigner son email dans le champ email :)

**Comment by hgwood** [comment]
Merci !
