### ISSUE TITLE
The video in the help doesn't work anymore

### ISSUE THREAD

**Issue by HassenMak** [Zenika/Zenika-Resume#20]
<img width="1193" alt="screen shot 2018-06-14 at 12 29 00 am" src="https://user-images.githubusercontent.com/36440134/41364699-f93104e0-6f69-11e8-991d-b6ce9283e02a.png">

**Comment by hgwood** [comment]
We should remove it then. I don't know where to recover.

**Comment by DhrubajitPC** [comment]
new video is up so closing this issue
