### ISSUE TITLE
Mettre les logos Zenika à jour ainsi que le style du CV

### ISSUE THREAD

**Issue by jlandure** [Zenika/Zenika-Resume#25]
c'est moche 😅

**Comment by hgwood** [comment]
Je crois que @CapsHil est sur le coup.

**Comment by CapsHil** [comment]
Hello Julien !

Effectivement, c'est très moche ;) De plus, l'export en PDF ne fonctionne manifestement pas bien du tout, des sauts de page s'ajoute à la fin de chaque paragraphe...

J'ai vu avec le market, et je vais faire une PR d'ici peu pour embellir un peu le truc (mettre le bon logo, les couleurs actuelles de Znk, etc), mais je ne suis pas sûr d'avoir le temps de me pencher sur le problème de la génération PDF.

**Comment by T3kstiil3** [comment]
Hello j'ai pris le sujet:
- Possibilité de changer de thèmes 
- Avoir une version en / fr de son cv (pratique sur Montreal)

https://github.com/Zenika/Zenika-Resume/pull/27

PS: c'est encore en WIP mais les retours sont les bienvenues, pour le moment le style que j'ai fait est simple, si vous avez des idées je prends 😀👍

**Comment by hgwood** [comment]
Closed by #27.
