### ISSUE TITLE
Problème de rendu à l'impression

### ISSUE THREAD

**Issue by zlgouyou** [Zenika/Zenika-Resume#37]
Le rendu à l'impression n'a rien avoir avec celui de l’aperçu.
Par exemple le logo Zenika disparaît.
![appercu](https://user-images.githubusercontent.com/22802938/48404066-b91d8980-e72f-11e8-9c35-6dbfe89bc3f7.PNG)
![appercu2](https://user-images.githubusercontent.com/22802938/48404067-b91d8980-e72f-11e8-98a2-800bfc972c94.PNG)
[zenika-resume.pdf](https://github.com/Zenika/Zenika-Resume/files/2575559/zenika-resume.pdf)
[zenika-resume-2.pdf](https://github.com/Zenika/Zenika-Resume/files/2575560/zenika-resume-2.pdf)

**Comment by zlgouyou** [comment]
solution : sous chrome il faut activer les graphique d’arrière plan dans les options d'impression
![capture](https://user-images.githubusercontent.com/22802938/48405089-ed924500-e731-11e8-90fc-6480dbb0d634.PNG)

**Comment by hgwood** [comment]
Tout ceci est préciser dans l'aide de l'application mais c'est vrai que le lien est petit (en bas à droite). :)
