### ISSUE TITLE
ajouter des nouvelles sections

### ISSUE THREAD

**Issue by ksouf** [Zenika/Zenika-Resume#4]
hello,

plusieures sections à prévoir : audit, speaking, certifications et formations.

Khaled

**Comment by ggaulard** [comment]
Alors ou ce situerai ces nouvelles sections?

En dehors des marquer 'experience' si tu ajoute un titre '# mon titre' puis tu met le contenu qui t'interesse cela ne répond pas au besoin ? (la le soucis c'est que le style des titres s'applique en dehors des sections d'experience)

On peux ajouter d'autres marquer pour mettre en place des formatage différents, mais l'objectif serait de rester simple.

**Comment by ggaulard** [comment]
les sections sont maintenant générique et il est possible d'indiquer leurs titres
