### ISSUE TITLE
Ajouter une entrée DNS sur zenika.com

### ISSUE THREAD

**Issue by ggerbaud** [Zenika/Zenika-Resume#5]
Utiliser une URL en zenika.com

Je propose resume.zenika.com

WDYT ?

**Comment by ggaulard** [comment]
Ce serait top.
Il me semble que cela se configure sur heroku.

**Comment by ggerbaud** [comment]
Ok, tu peux regarder pour la config coté heroku, je ferai pointer le domaine ensuite.
Il me faudra une IP ou sans doute un CNAME

**Comment by jlandure** [comment]
done! ✅ 
`https://resume.zenika.com`
