### ISSUE TITLE
CV not editable and not readable

### ISSUE THREAD

**Issue by gwenker** [Zenika/Zenika-Resume#60]
When i try to edit/view my CV, I just see a JSON instead of the content :

![image](https://user-images.githubusercontent.com/16991028/82303807-bc946f80-99bb-11ea-90e5-ced4669c9495.png)

URL to see my CV : https://resume.zenika.com/#/app/gwenole-kerninon-zenika-rennes-fr

Some people have encountered the same issue but after many try, they finally could access to content.

**Comment by hgwood** [comment]
Looks like a conflict between an old ("encrypted") version of the resume that was still in local storage overrode the one (unecrypted) in the database. I've sent you your resume by email.
